### ISSUE TITLE
could you make a flatpak for Tunlookup?

### ISSUE THREAD

**Issue by ghost** [thephucit/tunlookup#2]
Hi, I really appreciate your work , is a good application
i saw that you are planing to create a linux version of Tunlookup
could you make a flatpak for Tunlookup?
in this way, users can install the application in any linux distribution

please.
thank you.

**Comment by tun-application** [comment]
@chemel9 Thank for your suggestion, I will make linux version when I have time.
Can you let me know which version you're using and which version you love? (Tunlookup ver 1.x OR 2.X) ?
