### ISSUE TITLE
Application blocked

### ISSUE THREAD

**Issue by bouhlal** [thephucit/tunlookup#5]
the application allow you to translate only 14 times and after does not work

**Comment by thephucit** [comment]
@bouhlal I knew this problem, it block about 15 minutes
Because, Tunlookup using google translate public api and Tunlookup is a free application
so, I have no profit to upgrate translate api.
Sorry about that.

**Comment by bouhlal** [comment]
can you tray to use Yandex API I think it does not block ?

**Comment by thephucit** [comment]
Thanks, I would consider moving over there

**Comment by bouhlal** [comment]
also you can add option if the user would like to add his own api and use multiple services at the same time: google bing Yandex ...

**Comment by thephucit** [comment]
> also you can add option if the user would like to add his own api and use multiple services at the same time: google bing Yandex ...

Good suggestion, thank you.
Are you developer?

**Comment by bouhlal** [comment]
You are most welcome :)
yes, I am a developer.

**Comment by thephucit** [comment]
I would like invite you become maintainer for Tunlookup project,
Do you wanna join?

**Comment by bouhlal** [comment]
bouhlal@gmail.com lets talk private
