### ISSUE TITLE
Crashing on Windows 10

### ISSUE THREAD

**Issue by diegovdev** [thephucit/tunlookup#6]
Hi thanks for developing this!

In Windows 10 Enterprise after installing Tunlookup.Setup.3.1.0.exe I was never able to see the Tunlookup window trying with both shortcut options. I know that before I was using QTranslate that also uses Ctrl+Q so I closed it and still not working.

No log files in the Tunlookup install folder nor in this folder \AppData\Roaming\Tunlookup\logs.

All I coud find using Procmon is this `RaiseExceptionOnPossibleDeadlock` :

![2020-09-09_122902](https://user-images.githubusercontent.com/1246341/92626925-a1b27780-f298-11ea-83b2-acb1840f80b1.png)

**Comment by thephucit** [comment]
I'm not sure, but you can try remove both app and restart your computer before re-install Tunlookup.
