### ISSUE TITLE
A javascript occurred in the main process

### ISSUE THREAD

**Issue by milan96129** [thephucit/tunlookup#7]
Hello sir,
When i launch program it gives error like "A javascript occurred in the main process"
I tried to install microsoft c++ redistributable, but they didn't work. Also tried some youtube video, but no luck. Please give me some solution so that i can use this software for my upcoming exam.
![A javascript occurred in the main process Error](https://i.postimg.cc/xT8b80cb/java-error.jpg)

**Comment by thephucit** [comment]
Hi @milan96129 Are you currently using any third-party typing software?

**Comment by milan96129** [comment]
I use Microsoft I​ndic Language Input Tool for local lang where i need to type in Gujarati (Mother tounge)
![Gujarati](https://i.postimg.cc/qB2PbM3V/guj.jpg)

Here is link :
https://www.microsoft.com/en-in/bhashaindia/downloads.aspx#:~:text=Dow%E2%80%8Bn%E2%80%8Bload-,Gujarati,-Download

**Comment by thephucit** [comment]
Please try switching the input method to English, then turn it off and restart the Tunlookup application. In the past, when using Windows, I also frequently encountered unexpected errors with third-party input methods.

**Comment by milan96129** [comment]
No luck.
Is there any necessary to install microsoft c++  x86 for this software ?
I have C++ of x64 bit.

**Comment by thephucit** [comment]
You don't need to install anything else, it seems to be a bug from the 3.2.0 release. Please uninstall it and try installing version 3.1.0 instead. I will release a patch for this issue when I have time.

https://github.com/thephucit/tunlookup/releases/tag/v3.1.0

**Comment by milan96129** [comment]
Thank you so much. Its working now
